
//GET http://localhost:3002/aluno/todos

POST http://localhost:3002/novoUsuario
Content-Type: application/json

{
    "username": "usuario@outlook.com",
    "passwd": "usuario",
    "nome": "usuario"
}