POST http://localhost:3002/clientes
Content-Type: application/json
Authorization: Bearer {{token}}
@token = ""

{
  "nome": "João Silva",
  "cpf_cnpj": "12345678900",
  "telefone": "4799999999",
  "email": "joao@example.com",
  "cep": "89000000",
  "rg": "1234567",
  "nascimento": "1990-01-01",
  "contribuinte": "Sim",
  "inscricao_estadual": "987654321"
}

