
//GET http://localhost:3002/aluno/todos

POST http://localhost:3002/novoUsuario
Content-Type: application/json

{
    "username": "admin@outlook.com",
    "passwd": "administrador",
    "nome": "admin"
}