CREATE TABLE permissao
(
  id bigint  NOT NULL,
  descricao varchar NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE usuario
(
  email varchar NOT NULL,
  nome varchar NOT NULL,
  senha varchar NOT NULL,
  PRIMARY KEY (email)
);

CREATE TABLE usuario_permissao
(
  email varchar NOT NULL,
  id_permissao bigint NOT NULL,
  PRIMARY KEY (email, id_permissao),
  CONSTRAINT fk_usuario_permissao_usuario FOREIGN KEY (email) 
      REFERENCES usuario (email),
  CONSTRAINT fk_usuario_permissao_permissao FOREIGN KEY (id_permissao) 
      REFERENCES permissao (id)
);

CREATE TABLE servicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  preco NUMERIC(10,2) NOT NULL
);

CREATE TABLE cliente (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf_cnpj VARCHAR(20),
    telefone VARCHAR(20),
    email VARCHAR(100),
    cep VARCHAR(20),
    rg VARCHAR(20),
    nascimento DATE,
    contribuinte VARCHAR(10),
    inscricao_estadual VARCHAR(50)
);

CREATE TABLE ordem_servico (
    id SERIAL PRIMARY KEY,
    id_cliente INT NOT NULL,

    equipamento VARCHAR(255),
    marca VARCHAR(100),
    modelo VARCHAR(100),
    numero_serie VARCHAR(100),
    defeito VARCHAR(255),
    perifericos VARCHAR(255),
    senha VARCHAR(255),

    status VARCHAR(30) DEFAULT 'ABERTA',

    criado_em TIMESTAMP DEFAULT NOW(),

    FOREIGN KEY (id_cliente) REFERENCES cliente(id)
);

CREATE TABLE ordem_servico_item (
    id SERIAL PRIMARY KEY,
    id_ordem INT NOT NULL,
    id_servico INT NOT NULL,

    quantidade INT NOT NULL DEFAULT 1,
    preco NUMERIC(10, 2) NOT NULL,

    FOREIGN KEY (id_ordem) REFERENCES ordem_servico(id) ON DELETE CASCADE,
    FOREIGN KEY (id_servico) REFERENCES servicos(id)
);


-- INSERE USUARIOS
--usuario admin@outlook.com
--senha   Administrador
INSERT INTO usuario (email, nome, senha) 
VALUES ('admin@outlook.com', 'Administrador', '$2b$10$mHBljwcXFAHfT73HXh5FZOZsgsqmiBGrLALB3qJhSzJ3CLCqWoN8K');

--usuario usuario@outlook.com
--senha   usuario
INSERT INTO usuario (email, nome, senha) 
VALUES ('usuario@outlook.com', 'usuario', '$2b$10$V1OXzHqOoG0QJSfN3Iqp6.IXJ5/QVHIAsjBFeA9DVWdrVv1Fyod0u');

-- INSERE PERMISSAO ANTES DE TUDO
INSERT INTO permissao (id, descricao) 
VALUES (1, 'VER');
VALUES (2, 'EDITAR');
VALUES (3, 'CRIAR');
VALUES (4, 'DELETAR');


-- INSERE RELACIONAMENTO
INSERT INTO usuario_permissao (email, id_permissao) 
VALUES ('usuario@outlook.com', 1);
VALUES ('admin@outlook.com', 1);
VALUES ('admin@outlook.com', 2);
VALUES ('admin@outlook.com', 3);
VALUES ('admin@outlook.com', 4);

-- isere serviços
INSERT INTO servicos (id, nome, descricao, preco)
VALUES (1, 'Formatação de Notebook','Formatação completa com backup e reinstalação de sistema', 150.00);

INSERT INTO servicos (id, nome, descricao, preco)
VALUES (2, 'Troca de Tela de Celular', 'Substituição de tela quebrada por peça original', 250.00);

INSERT INTO servicos (id, nome, descricao, preco)
VALUES (3, 'Limpeza de Computador', 'Limpeza física interna e otimização de desempenho', 80.00);
